# Generated by Django 5.1.2 on 2025-04-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_alter_antropometria_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitoAlimenticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.CharField(max_length=50)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('frecuencia', models.CharField(choices=[('dia', 'Día'), ('semana', 'Semana'), ('mes', 'Mes'), ('nunca', 'Nunca')], max_length=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
