# Generated by Django 5.1.2 on 2025-04-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_alter_antropometria_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_farmaco', models.CharField(max_length=100)),
                ('nombre_generico', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=100)),
                ('via', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='pacientes.paciente')),
            ],
        ),
    ]
