# Generated by Django 5.1.7 on 2025-03-18 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('escolaridad', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('vegetariano', models.BooleanField(default=False)),
                ('embarazo', models.BooleanField(default=False)),
                ('deportista', models.BooleanField(default=False)),
                ('adulto_mayor', models.BooleanField(default=False)),
                ('pediatrico', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nutriologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
