# Generated by Django 5.1.7 on 2025-03-31 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antropometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('relacion_cc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grasa_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
