# Generated by Django 5.1.2 on 2025-03-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_antropometria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='antropometria',
            unique_together={('paciente', 'fecha')},
        ),
    ]
