# Generated by Django 5.1.2 on 2025-04-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_antropometria_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Antropometria',
        ),
    ]
