# Generated by Django 5.1.2 on 2025-01-01 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="El número debe tener entre 9 y 15 dígitos y puede incluir '+' al inicio.", regex='^\\+?1?\\d{9,11}$')]),
        ),
    ]
