# Generated by Django 5.1.2 on 2025-04-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alergias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergia',
            name='gravedad',
            field=models.CharField(blank=True, choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alergia',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
