# Generated by Django 5.1.2 on 2025-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bioquimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('valor_inferior_normal', models.FloatField()),
                ('valor_superior_normal', models.FloatField()),
                ('tratamiento_deficiente', models.TextField()),
                ('tratamiento_superior', models.TextField()),
                ('bibliografia', models.TextField()),
            ],
        ),
    ]
