# Generated by Django 5.1.2 on 2025-04-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0005_delete_antropometria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentePatologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.JSONField(default=dict)),
                ('hipertension', models.JSONField(default=dict)),
                ('colesterolemia', models.JSONField(default=dict)),
                ('trigliceridemia', models.JSONField(default=dict)),
                ('obesidad', models.JSONField(default=dict)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='OtraEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presencia', models.JSONField(default=dict)),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otras_enfermedades', to='antecedentesPatologicos.antecedentepatologico')),
            ],
        ),
    ]
