# Generated by Django 5.1.2 on 2025-03-31 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_alter_antropometria_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toxicomania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.BooleanField(default=False)),
                ('alcohol_veces', models.IntegerField(blank=True, null=True)),
                ('alcohol_frecuencia', models.CharField(choices=[('nunca', 'Nunca'), ('diario', 'Diario'), ('semana', 'Semanal'), ('mes', 'Mensual'), ('año', 'Anual')], default='nunca', max_length=10)),
                ('tabaco', models.BooleanField(default=False)),
                ('tabaco_veces', models.IntegerField(blank=True, null=True)),
                ('tabaco_frecuencia', models.CharField(choices=[('nunca', 'Nunca'), ('diario', 'Diario'), ('semana', 'Semanal'), ('mes', 'Mensual'), ('año', 'Anual')], default='nunca', max_length=10)),
                ('otro', models.CharField(blank=True, max_length=100)),
                ('otro_check', models.BooleanField(default=False)),
                ('otro_veces', models.IntegerField(blank=True, null=True)),
                ('otro_frecuencia', models.CharField(choices=[('nunca', 'Nunca'), ('diario', 'Diario'), ('semana', 'Semanal'), ('mes', 'Mensual'), ('año', 'Anual')], default='nunca', max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
