# Generated by Django 5.1.2 on 2025-03-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxicomanias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxicomania',
            name='alcohol_frecuencia',
            field=models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('diario', 'Diario'), ('semana', 'Semanal'), ('mes', 'Mensual'), ('año', 'Anual')], default='nunca', max_length=10),
        ),
        migrations.AlterField(
            model_name='toxicomania',
            name='otro_frecuencia',
            field=models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('diario', 'Diario'), ('semana', 'Semanal'), ('mes', 'Mensual'), ('año', 'Anual')], default='nunca', max_length=10),
        ),
        migrations.AlterField(
            model_name='toxicomania',
            name='tabaco_frecuencia',
            field=models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('diario', 'Diario'), ('semana', 'Semanal'), ('mes', 'Mensual'), ('año', 'Anual')], default='nunca', max_length=10),
        ),
    ]
