# Generated by Django 5.1.2 on 2025-04-02 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_enfer', models.TextField()),
                ('tratamiento_nut', models.TextField()),
                ('bibliografia', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('nutriologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
